### ISSUE TITLE
Steeleaf knife id typo messes registry [v2.4-1.19.2]

### ISSUE THREAD

**Issue by LizzieSpace** [ianm1647/farmersknives#8]
```[08:17:23] [main/ERROR]: Parsing error loading recipe farmersknives:steeleaf_knife
com.google.gson.JsonSyntaxException: Unknown item 'twilightforest:stealeaf_ingot'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
[...]
```
the id for steeleaf_ingot is mistyped, causing the registry to throw.

 current version is latest release for 1.19.2

**Comment by ianm1647** [comment]
fixed
